- name: install shell tools
  become: true
  apt:
    pkg:
      - fzf

# nano
- name: install nano rc
  become_user: jason
  copy:
    src: files/.nanorc
    dest: ~/.nanorc
    mode: '644'
    owner: jason
    group: jason

# better terminal + tmux
- name: install command line apt packages (fish, powerline, tmux)
  become: true
  apt:
    pkg:
      - fish
      - powerline
      - tmux

- name: tmux config
  become_user: jason
  git:
    repo: https://github.com/gpakosz/.tmux.git
    dest: ~/.tmux
    version: 3bfec1a25a8a66dd251d37f4efcd6a0e9f30a6da

- name: tmux link
  become_user: jason
  file:
    src: ~/.tmux/.tmux.conf
    dest: ~/.tmux.conf
    state: link
    owner: jason
    group: jason

- name: tmux config local
  become_user: jason
  copy:
    src: files/.tmux.conf.local
    dest: ~/.tmux.conf.local
    mode: '644'
    owner: jason
    group: jason

- name: install oh-my-fish
  git:
    repo: https://github.com/oh-my-fish/oh-my-fish.git
    dest: ~/.local/share/omf-install
    update: true
    version: 0b1396ad7962073fa25615bf03c43b53eddc2d56

  become: true
  become_user: jason

- name: install oh-my-fish themes and plugins
  command: >
    fish -c "~/.local/share/omf-install/bin/install --noninteractive --yes"
  args:
    creates: ~/.local/share/omf/themes/default/
  become: true
  become_user: jason

- name: install bob the fish theme
  command: fish -c "omf install bobthefish"
  args:
    creates: /home/jason/.local/share/omf/themes/bobthefish/
  become: true
  become_user: jason

- name: Create fish functions directory
  become_user: jason
  file:
    path: /home/jason/.config/fish/functions
    state: directory

- name: Add fish keybindings for fzf
  lineinfile:
    dest: /home/jason/.config/fish/functions/fish_user_key_bindings.fish
    owner: jason
    create: yes
    line: "fzf_key_bindings"

- name: install forgit for fish
  command: fish -c "omf install https://github.com/wfxr/forgit"
  args:
    creates: /home/jason/.local/share/omf/pkg/fo
  become: true
  become_user: jason

# bashrc updates for fzf (see /usr/share/doc/fzf/README.Debian)
# and forgit: https://github.com/wfxr/forgit
- name: Update bashrc fzf
  lineinfile:
    dest: /home/jason/.bashrc
    owner: jason
    line: "{{ item }}"
  with_items:
    - "source /usr/share/doc/fzf/examples/key-bindings.bash"
    - "source /usr/share/doc/fzf/examples/completion.bash"
    - "source <(curl -sSL git.io/forgit)"
