- name: FlareSolver
  tags: flaresolver
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  community.docker.docker_container:
    name: flaresolver
    image: ghcr.io/flaresolverr/flaresolverr:latest
    pull: true
    ports:
      - "8191:8191"
    env:
      CAPTCHA_SOLVER: "hcaptcha-solver"
    restart_policy: unless-stopped
