# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#inventory-basics-formats-hosts-and-groups
# I prefer the yaml formatting because it makes the `all` and `ungrouped` more
# explicit than the ini version.
all:
  hosts:
    # this is where ungrouped hosts would go
  children:
    development:
      hosts:
        ubuntu-desktop:
        jason-ubuntu-laptop:
        jason-work-laptop:
    development-gui:
      hosts:
        ubuntu-desktop:
        jason-ubuntu-laptop:
        jason-work-laptop:
