# note: this requires the host to have the nvenv nvidia patch if it is a consumer
# nvidia card: https://github.com/keylase/nvidia-patch
- name: Deploy Livepeer Transcoder with Nvidia GPU
  tags: livepeer
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  community.docker.docker_container:
    name: livepeer
    image: livepeer/go-livepeer:master
    pull: true
    restart_policy: unless-stopped
    device_requests:
      - driver: nvidia
        count: -1
        capabilities:
          - gpu
    command: -transcoder -nvidia 0 -orchSecret {{ orchSecret }} -orchAddr jasonernst.com:8935 -monitor -ethAcctAddr 0x74ba897f65f04008d8eff364efcc54b0a20e17eb
    volumes:
      - "/root/.ethereum:/root/.ethereum"
