# https://serverfault.com/a/832850
- name: Update the /etc/hosts file with node name
  tags: etchostsupdate
  become: true
  lineinfile:
    path: "/etc/hosts"
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
    backup: yes
  register: etchostsupdate
  when: hostvars[item].ansible_host is defined
  with_items: "{{groups['home']}}"
