---
- name: install various tools
  become: true
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - curl                    # command line http tool
      - wget                    # command line http tool

- name: install network tools
  become: true
  apt:
    pkg:
      - arp-scan                # for ip <-> mac map search
      - dnsutils                # dig
      - ethtool                 # gets info like link speed
      - iftop                   # network top
      - iotop                   # disk top
      - net-tools               # ifconfig, netstat, arp
      - nmap                    # determine open ports
      - traceroute              # traceroute
      - nbtscan                 # netbios scanner
      - speedtest-cli           # bandwidth debugging
      - sshuttle                # forward ssh through tunnel
      - whois                   # whois
      - sqlite3                 # good db for integration tests
      - socat                   # sort of like nc but doesn't hang
      - sshfs                   # ssh mounts

# https://github.com/nickjj/ansible-docker
- name: Ensure docker is installed on the target system
  include_role:
    name: nickjj.docker
    apply:
      become: true

- name: Add the user 'jason'
  become: true
  ansible.builtin.user:
    name: jason
    comment: Jason Ernst

- name: adding jason to group sudo
  become: true
  user:
    name: jason
    groups: sudo
    append: true

- name: adding jason to group docker
  become: true
  user:
    name: jason
    groups: docker
    append: true

# pgp keys see: https://github.com/netson/ansible-gpg-key
# and https://github.com/cpmills1975/ansible-gpg-import-module
# and https://github.com/brandonkal/ansible-gpg
- name: Create gpg directory if it does not exist
  become_user: jason
  file:
    path: ~/.gpg
    state: directory
    mode: '0755'
    owner: jason
    group: jason

- name: gpg pub key copy
  become_user: jason
  copy:
    src: files/gpg/mygpgkey_pub.gpg
    dest: ~/.gpg/mygpgkey_pub.gpg
    mode: '0600'
    owner: jason
    group: jason

- name: gpg priv key copy
  become_user: jason
  copy:
    src: files/gpg/mygpgkey_sec.gpg
    dest: ~/.gpg/mygpgkey_sec.gpg
    mode: '0600'
    owner: jason
    group: jason

- name: import Public GPG Key from file
  become_user: jason
  gpg:
    key_file: ~/.gpg/mygpgkey_pub.gpg
    key_id: ernstjason1@gmail.com

- name: import private GPG Key from file
  become_user: jason
  gpg:
    key_file: ~/.gpg/mygpgkey_sec.gpg
    key_id: ernstjason1@gmail.com
    key_type: private

# enables the target to ssh into other machines I've deployed via ssh key
# ie: no password required
- name: ssh id_rsa
  become_user: jason
  copy:
    src: files/ssh/id_rsa
    dest: ~/.ssh/id_rsa
    mode: '0600'
    owner: jason
    group: jason

- name: ssh id_rsa.pub
  become_user: jason
  copy:
    src: files/ssh/id_rsa.pub
    dest: ~/.ssh/id_rsa.pub
    mode: '0644'
    owner: jason
    group: jason

- name: Create /root/.ssh/config file if it does not exist
  become: true
  file:
    path: /root/.ssh/config
    state: present
    mode: '0600'
    owner: root
    group: root

- name: root ssh id_rsa
  become: true
  copy:
    src: files/ssh/id_rsa
    dest: /root/.ssh./id_rsa
    mode: '0600'
    owner: root
    group: root

- name: root ssh id_rsa.pub
  become: true
  copy:
    src: files/ssh/id_rsa.pub
    dest: /root/.ssh/id_rsa.pub
    mode: '0644'
    owner: root
    group: root
