- name: Deploy lolminer for Nvidia GPU
  tags: mining
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  community.docker.docker_container:
    name: lolminer
    image: compscidr/lolminer-docker:nvidia-1.52-c11.4.2
    pull: true
    restart_policy: unless-stopped
    device_requests:
      - driver: nvidia
        count: -1
        capabilities:
          - gpu
    ports:
      - 4069:4069
    entrypoint: |
      /lolminer/lolMiner --coin ETH --pool eth.2miners.com --port 2020
      --user 0x74ba897f65f04008d8eff364efcc54b0a20e17eb.{{ inventory_hostname }} --apihost 0.0.0.0 --apiport 4069
      --watchdog exit --tstop 92
    init: true
