- name: install gui development tools
  become: yes
  apt:
    pkg:
    - wireshark

- name: Ensure group wireshark exists
  become: yes
  group:
    name: wireshark
    state: present

- name: adding jason to group wireshark
  become: yes
  user:
    name: jason
    groups: wireshark
    append: yes

- name: install zoom
  become: yes
  apt:
    deb: https://zoom.us/client/latest/zoom_amd64.deb

- name: install keybase
  become: yes
  apt:
    deb: https://prerelease.keybase.io/keybase_amd64.deb

- name: install chrome browser
  become: yes
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Ensure jetbrains toolbox is installed on the target system
  include_role:
    name: ansible-role-jet-brains-toolbox
    apply:
      become: yes

- name: install slack
  become: yes
  apt:
    deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.14.0-amd64.deb

- name: Install spotify apt keys
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 8FD3D9A8D3800305A9FFF259D1742AD60D811D58
    state: present

- name: Install spotify apt repo
  become: yes
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present

- name: Install spotify
  become: yes
  apt: update_cache=yes name=spotify-client state=latest
  register: apt_res
  until: apt_res is success
  retries: 5
  delay: 60

- name: install atom editor
  become: yes
  apt:
    deb: https://atom.io/download/deb
