- name: add zig repository
  tags: zig
  become: true
  apt_repository:
    repo: "deb [trusted=yes] https://apt.fury.io/compscidr/ /"
    state: present
    update_cache: true

- name: update apt and install zig
  tags: zig
  become: true
  apt:
    update_cache: true
    name: zig
    state: present
