- name: Install node development tools
  become: true
  ansible.builtin.apt:
    pkg:
      - npm

# yarn: https://www.itzgeek.com/how-tos/linux/ubuntu-how-tos/how-to-install-yarn-on-ubuntu-22-04-ubuntu-20-04.html
# https://docs.ansible.com/ansible/latest/collections/community/general/npm_module.html
- name: Install yarn node.js package
  become: true
  community.general.npm:
    name: yarn
    global: yes
