- name: Install node development tools
  become: true
  ansible.builtin.apt:
    pkg:
      - npm

# yarn: https://www.itzgeek.com/how-tos/linux/ubuntu-how-tos/how-to-install-yarn-on-ubuntu-22-04-ubuntu-20-04.html
# https://docs.ansible.com/ansible/latest/collections/community/general/npm_module.html
- name: Install yarn node.js package
  become: true
  tags: yarn
  community.general.npm:
    name: yarn
    global: true

- name: Install tldr node package # https://tldr.sh/
  become: true
  tags: tldr
  community.general.npm:
    name: tldr
    global: true

- name: Create a tldr symbolic link
  become: true
  tags: tldr
  ansible.builtin.file:
    src: /usr/local/bin/tldr
    dest: /usr/bin/tldr
    owner: root
    group: root
    state: link
