# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#inventory-basics-formats-hosts-and-groups
# I prefer the yaml formatting because it makes the `all` and `ungrouped` more
# explicit than the ini version.
all:
  children:
    home:
      hosts:
        ubuntu-server:
          ansible_host: 10.0.0.116
          ansible_user: jason
        ubuntu-desktop-beast:
          ansible_host: 10.0.0.89
          ansible_user: jason
        ubuntu-desktop:
          ansible_host: 10.0.0.111
          ansible_user: jason
        jason-ubuntu-laptop:
          ansible_host: 10.0.0.17
          ansible_user: jason
        ubuntu-work-laptop:
          ansible_host: 10.0.0.103
          ansible_user: jason
