- name: Create Livepeer Directories
  tags: livepeer
  file:
    path: /root/.lpData/mainnet/keystore
    state: directory

- name: Copy Ethereum Wallet to Livepeer
  tags: livepeer
  copy:
    src: files/UTC--2016-03-12T21-58-48.509345400Z--74ba897f65f04008d8eff364efcc54b0a20e17eb
    dest: /root/.lpData/mainnet/keystore/UTC--2016-03-12T21-58-48.509345400Z--74ba897f65f04008d8eff364efcc54b0a20e17eb
    mode: '0600'

- name: Deploy Livepeer Orchestrator (with optional transcoder running too)
  tags: livepeer
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  community.docker.docker_container:
    name: livepeer
    image: livepeer/go-livepeer:master
    pull: true
    restart_policy: unless-stopped
    ports:
      - 8935:8935
      - 7935:7935
    command: -network mainnet -ethUrl https://mainnet.infura.io/v3/{{ infura_secret }} -ethAcctAddr 0x74ba897f65f04008d8eff364efcc54b0a20e17eb -orchestrator -pricePerUnit 995 -serviceAddr lp.jasonernst.com:8935 -reward=false -orchSecret {{ orchSecret }} --ethPassword {{ ethPassword }} -monitor --cliAddr 0.0.0.0:7935
    volumes:
      - "/root/.lpData:/root/.lpData"
    etc_hosts:
      lp.jasonernst.com: 127.0.0.1
      jasonernst.com: 172.17.0.1
