- name: Create Ombi Directories
  file:
    mode: '755'
    path: /etc/ombi
    state: directory

- name: Ombi Docker Container
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  docker_container:
    name: ombi
    image: linuxserver/ombi:latest
    pull: true
    volumes:
      - "/etc/ombi:/config:rw"
    env:
      TZ: "America/Los_Angeles"
      PUID: "0"
      PGID: "0"
      VIRTUAL_HOST: "ombi.jasonernst.com"
      VIRTUAL_PORT: "3579"
      LETSENCRYPT_HOST: "ombi.jasonernst.com"
      LETSENCRYPT_EMAIL: "ernstjason1@gmail.com"
    restart_policy: unless-stopped
    memory: "1g"
