- name: pull and run the nginx reverse proxy
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  docker_container:
    name: nginx-proxy
    image: jwilder/nginx-proxy
    published_ports: 80:80,443:443
    volumes: >
      conf:/etc/nginx/conf.d,
      vhost:/etc/nginx/vhost.d,
      html:/usr/share/nginx/html,
      dhparam:/etc/nginx/dhparam,
      certs:/etc/nginx/certs:ro,
      /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge

- name: pull and run the lets encypt companion to the proxy
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  docker_container:
    name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes: >
      certs:/etc/nginx/certs:rw,
      /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from: nginx-proxy
    network_mode: bridge

# todo: move this perhaps to a db role so that websites without dbs don't need it
- name: pull and run the mysql db
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  docker_container:
    name: mysql
    image: mysql
    env:
      MYSQL_ROOT_PASSWORD: rootpassword
    network_mode: bridge
