# wireshark
- name: install wireshark
  tags: wireshark
  become: true
  apt:
    pkg:
    - wireshark

- name: Ensure group wireshark exists
  become: true
  tags: wireshark
  group:
    name: wireshark
    state: present

- name: adding jason to group wireshark
  become: true
  tags: wireshark
  user:
    name: jason
    groups: wireshark
    append: yes

# bloomrpc
- name: install bloomrpc
  become: true
  tags: bloomrpc
  apt:
    deb: https://github.com/uw-labs/bloomrpc/releases/download/1.5.2/bloomrpc_1.5.2_amd64.deb

# keybase
- name: install keybase
  tags: keybase
  become: true
  apt:
    deb: https://prerelease.keybase.io/keybase_amd64.deb

# chrome
- name: install chrome browser
  tags: chrome
  become: true
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

# slack
- name: install slack
  tags: slack
  become: true
  apt:
    deb: https://downloads.slack-edge.com/releases/linux/4.21.1/prod/x64/slack-desktop-4.21.1-amd64.deb

# spotify
- name: Install spotify apt keys
  tags: spotify
  become: true
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 8FD3D9A8D3800305A9FFF259D1742AD60D811D58
    state: present

- name: Install spotify apt repo
  tags: spotify
  become: true
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present

- name: Install spotify
  tags: spotify
  become: true
  apt: update_cache=yes name=spotify-client state=latest
  register: apt_res
  until: apt_res is success
  retries: 5
  delay: 60

# texmaker
- name: install texmaker
  tags: latex
  become: true
  apt:
    pkg:
      - texmaker
      - fonts-font-awesome
      - texlive-fonts-recommended
      - texlive-fonts-extra

# zoom
- name: install zoom
  tags: zoom
  become: true
  apt:
    deb: https://zoom.us/client/latest/zoom_amd64.deb

# discord
- name: install discord
  tags: discord
  become: true
  apt:
    deb: https://discordapp.com/api/download?platform=linux&format=deb
