ungrouped: {}
all:
  children:
    lan:
      hosts:
        ubuntu-server:
          ansible_host: 10.0.0.218
          max_temp: 91
# Used in case this is run from outside of the home network
#          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q jason@home.jasonernst.com"'
        ubuntu-desktop-beast:
          ansible_host: 10.0.0.89
          max_temp: 92
# Used in case this is run from outside of the home network
#          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q jason@home.jasonernst.com"'
        ubuntu-desktop:
          ansible_host: 10.0.0.111
          max_temp: 90
        jason-ubuntu-laptop:
          ansible_host: 10.0.0.17
        jason-work-ubuntu:
          ansible_host: 127.0.0.1
    development:
      hosts:
        ubuntu-server:
        ubuntu-desktop-beast:
        ubuntu-desktop:
        jason-ubuntu-laptop:
        jason-work-ubuntu:
    development_gui:
      hosts:
        ubuntu-desktop:
        ubuntu-desktop-beast:
        jason-ubuntu-laptop:
        jason-work-ubuntu:
    amd:
      hosts:
        ubuntu-desktop:
        ubuntu-server:
    nvidia:
      hosts:
        ubuntu-desktop-beast:
    home_jasonernst_com:
      hosts:
        ubuntu-server:
    www_jasonernst_com:
      hosts:
        www.jasonernst.com:
    lp_jasonernst_com:
      hosts:
        lp.jasonernst.com:
    ombi_jasonernst_com:
      hosts:
        ombi.jasonernst.com:
