---
# file: site.yml
# sets up configuration and software across all environments
- hosts: all
  pre_tasks:
    - name: update apt cache if needed
      become: true
      apt:
        update_cache: true
        cache_valid_time: 86400
  roles:
    - common

- hosts: development
  tags: development
  pre_tasks:
    - name: update apt cache if needed
      become: true
      apt:
        update_cache: true
        cache_valid_time: 86400
  roles:
    - common
    - development

- hosts: development_gui
  tags: development_gui
  pre_tasks:
    - name: update apt cache if needed
      become: true
      apt:
        update_cache: true
        cache_valid_time: 86400
  roles:
    - development_gui

- hosts: compute
  pre_tasks:
    - name: update apt cache if needed
      become: true
      apt:
        update_cache: true
        cache_valid_time: 86400
  roles:
    - common

- hosts: www.jasonernst.com
  roles:
    - web

- hosts: ubuntu-server
  pre_tasks:
    - name: update apt cache if needed
      become: true
      apt:
        update_cache: true
        cache_valid_time: 86400
  roles:
    - common
    - home_server

- hosts: home
  gather_facts: true
  roles:
    - internal_lan

- hosts: ubuntu-server, ubuntu-desktop, ubuntu-desktop-beast
  roles:
    - mining

- hosts: ubuntu-server, ubuntu-desktop, jason-ubuntu-laptop
  roles:
    - chia
