---
# file: site.yml
# sets up configuration and software across all environments
- hosts: development
  pre_tasks:
    - name: update apt cache if needed
      become: true
      apt:
        update_cache: true
        cache_valid_time: 86400
  roles:
    - common
    - development

- hosts: development_gui
  pre_tasks:
    - name: update apt cache if needed
      become: true
      apt:
        update_cache: true
        cache_valid_time: 86400
  roles:
    - development_gui

- hosts: compute
  pre_tasks:
    - name: update apt cache if needed
      become: true
      apt:
        update_cache: true
        cache_valid_time: 86400
  roles:
    - common

- hosts: www.jasonernst.com
  roles:
    - web
  tasks:
    - name: pull and run the app container for www.jasonernst.com
      vars:
        ansible_python_interpreter: "/usr/bin/env python3-docker"
      docker_container:
        name: www.jasonernst.com
        image: compscidr/goblog:v0.1.11
        volumes: /opt/goblog/prod/uploads:/go/src/github.com/compscidr/goblog/uploads
        mounts:
          - source: /opt/goblog/prod/test.db
            target: /go/src/github.com/compscidr/goblog/test.db
            type: bind
          - source: /opt/goblog/prod/.env
            target: /go/src/github.com/compscidr/goblog/.env
            type: bind
        network_mode: bridge
        restart_policy: unless-stopped
        env:
          VIRTUAL_HOST: "www.jasonernst.com,jasonernst.com"
          VIRTUAL_PORT: "7000"
          LETSENCRYPT_HOST: "www.jasonernst.com,jasonernst.com"
          LETSENCRYPT_EMAIL: "ernstjason1@gmail.com"

    - name: Adds a crontab entry to to backup website
      ansible.builtin.cron:
        name: "backup www.jasonernst.com"
        minute: "0"
        hour: "3"
        job: "rsync -av --delete /opt/goblog/prod/ home.jasonernst.com:/storage/backup/www.jasonernst.com/"

    - name: Create Ombi Directories
      file:
        path: /etc/ombi
        state: directory

    - name: Ombi Docker Container
      vars:
        ansible_python_interpreter: "/usr/bin/env python3-docker"
      docker_container:
        name: ombi
        image: linuxserver/ombi:latest
        pull: true
        volumes:
          - "/etc/ombi:/config:rw"
        env:
          TZ: "America/Los_Angeles"
          PUID: "0"
          PGID: "0"
          VIRTUAL_HOST: "ombi.jasonernst.com"
          VIRTUAL_PORT: "3579"
          LETSENCRYPT_HOST: "ombi.jasonernst.com"
          LETSENCRYPT_EMAIL: "ernstjason1@gmail.com"
        restart_policy: unless-stopped
        memory: "1g"

- hosts: ubuntu-server
  pre_tasks:
    - name: update apt cache if needed
      become: true
      apt:
        update_cache: true
        cache_valid_time: 86400
  roles:
    - common
    - home_server

- hosts: home
  gather_facts: true
  roles:
    - internal_lan

- hosts: ubuntu-server, ubuntu-desktop, ubuntu-desktop-beast
  roles:
    - mining

- hosts: ubuntu-desktop
  roles:
    - chia
