- name: Create Jacket Directories
  tags: jackett
  become: true
  ansible.builtin.file:
    path: /etc/jackett
    state: directory
    mode: '755'
    owner: root
    group: root

- name: Deploy Jackett
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  community.docker.docker_container:
    name: jackett
    image: linuxserver/jackett:latest
    pull: true
    volumes:
      - "/etc/jackett:/config:rw"
      - "/storage/downloads:/downloads:rw"
    ports:
      - "9117:9117"
    links:
      flaresolver
    env:
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "1000"
      AUTO_UPDATE: "true"
    restart_policy: unless-stopped
    memory: "1g"
