- name: Deploy lolminer for AMD GPU
  tags: mining
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  docker_container:
    name: lolminer
    image: compscidr/lolminer-docker:amd-1.46a
    pull: true
    restart_policy: unless-stopped
    devices:
      - "/dev/dri:/dev/dri"
    ports:
      - 4069:4069
    env:
      MACHINE: "{{ inventory_hostname }}"
