name: Ansible Lint  # feel free to pick your own name

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: Install Ansible
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
        cache: 'pip'
    - run: pip install ansible-core==2.11.6 ansible-line==5.2.1
    - run: ansible-lint ansible
